/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/Accordion.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    ListBox: typeof import('./components/ListBox.vue')['default']
    LoadingCardSkeleton: typeof import('./components/LoadingCardSkeleton.vue')['default']
    Popover: typeof import('./components/Popover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
